// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW808WcpyBl7h7KBP3QI70C4AXj8vYQ3s',
    appId: '1:910065592969:web:113f25e63177a0718d7458',
    messagingSenderId: '910065592969',
    projectId: 'q8-uc-282108',
    authDomain: 'q8-uc-282108.firebaseapp.com',
    storageBucket: 'q8-uc-282108.appspot.com',
    measurementId: 'G-9FZJ175M1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkR_2rVySsJvqHlZ_lRZWaLXxcFpnsFQk',
    appId: '1:910065592969:android:fe27f83c30a9d97d8d7458',
    messagingSenderId: '910065592969',
    projectId: 'q8-uc-282108',
    storageBucket: 'q8-uc-282108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7xbko1yO3IZ9RJU1-RDqb33p8QqyImfw',
    appId: '1:910065592969:ios:e81a04397f3d5a828d7458',
    messagingSenderId: '910065592969',
    projectId: 'q8-uc-282108',
    storageBucket: 'q8-uc-282108.appspot.com',
    androidClientId: '910065592969-98cs1mp1l3jolhlj8iskfuo39a31frqd.apps.googleusercontent.com',
    iosClientId: '910065592969-dk2ktp28mim4214ub20oeplpm1jmlvh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
