// plugin imports
export 'package:google_fonts/google_fonts.dart';
export 'package:stacked/stacked.dart';
export 'package:line_icons/line_icons.dart';
export 'package:font_awesome_flutter/font_awesome_flutter.dart';
export 'package:carousel_slider/carousel_slider.dart';
export 'package:flutter_advanced_drawer/flutter_advanced_drawer.dart';
export 'package:http/http.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:firebase_core/firebase_core.dart';
//export 'package:file_picker/file_picker.dart';
export 'package:firebase_auth/firebase_auth.dart';
export'package:google_sign_in/google_sign_in.dart';
export 'package:cloud_firestore/cloud_firestore.dart';
export 'package:faker/faker.dart';
export 'package:ecommerce/firebase_options.dart';
export 'package:nonce/nonce.dart';
export 'package:html_unescape/html_unescape_small.dart';
export 'package:url_launcher/url_launcher.dart';
export 'package:ecommerce/model/utilities/functions/urlLauncher.dart';
